//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public int PurchaseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Paid { get; set; }
        public int Balence { get; set; }
    
        public virtual CustomerPurchasal CustomerPurchasal { get; set; }
    }
}
