//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardDetail()
        {
            this.CustomerPurchasals = new HashSet<CustomerPurchasal>();
        }
    
        public int CardNmber { get; set; }
        public int cvv { get; set; }
        public int CustId { get; set; }
        public string Name { get; set; }
        public System.DateTime ExpiraDate { get; set; }
        public int cardtype { get; set; }
        public int balence { get; set; }
        public byte Satus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPurchasal> CustomerPurchasals { get; set; }
        public virtual CardTypeMaster CardTypeMaster { get; set; }
        public virtual CustomerMaster CustomerMaster { get; set; }
    }
}
