//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FinanceDbEntities : DbContext
    {
        public FinanceDbEntities()
            : base("name=FinanceDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AdminUserDetailsMaster> AdminUserDetailsMasters { get; set; }
        public virtual DbSet<CardDetail> CardDetails { get; set; }
        public virtual DbSet<CardTypeMaster> CardTypeMasters { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<CustomerPurchasal> CustomerPurchasals { get; set; }
        public virtual DbSet<docMaster> docMasters { get; set; }
        public virtual DbSet<PayementPlan> PayementPlans { get; set; }
        public virtual DbSet<PayementSchedule> PayementSchedules { get; set; }
        public virtual DbSet<ProductList> ProductLists { get; set; }
        public virtual DbSet<ProductMaster> ProductMasters { get; set; }
        public virtual DbSet<userDoc> userDocs { get; set; }
    
        public virtual ObjectResult<proc_GetAllDetails_Result> proc_GetAllDetails(string username, string ans1, string ans2, string ans3)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var ans1Parameter = ans1 != null ?
                new ObjectParameter("ans1", ans1) :
                new ObjectParameter("ans1", typeof(string));
    
            var ans2Parameter = ans2 != null ?
                new ObjectParameter("ans2", ans2) :
                new ObjectParameter("ans2", typeof(string));
    
            var ans3Parameter = ans3 != null ?
                new ObjectParameter("ans3", ans3) :
                new ObjectParameter("ans3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetAllDetails_Result>("proc_GetAllDetails", usernameParameter, ans1Parameter, ans2Parameter, ans3Parameter);
        }
    
        public virtual int proc_UpdatePassword(Nullable<int> id, string password)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UpdatePassword", idParameter, passwordParameter);
        }
    }
}
