//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayementSchedule
    {
        public int id { get; set; }
        public int PurchasalId { get; set; }
        public System.DateTime payementDate { get; set; }
        public int Amount { get; set; }
        public byte Paid { get; set; }
    
        public virtual CustomerPurchasal CustomerPurchasal { get; set; }
    }
}
